server:
    port: 8089

api:
    finnhub:
        token: ck4fjshr01qus81pv3ogck4fjshr01qus81pv3p0
        domain: finnhub.io
        base-url: api/v1
        endpoints:
            stock:
                profile2: /stock/profile2
                quote: /quote
                symbol: /stock/symbol

redis-key:
    company-profile2: "demo-finnhub:companyprofile2"

spring.datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver

spring.jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
        
spring.sql.init.mode: always # always


